language: node_js

node_js:
  - "4.0"
  - "0.12"
  - "0.11"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8

before_script:
  - npm install

script:
  - travis_wait travis_retry istanbul cover ./node_modules/mocha/bin/_mocha test/connect test/core test/markets test/client --report lcovonly && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
