sudo: false

language: node_js

env:
  - CXX=g++-4.8

node_js:
  - "5.0"
  - "4.2"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8

before_script:
  - npm install

script:
  - npm run coverage
