sudo: false

language: node_js

node_js:
  - "8"
  - "6"

before_script:
  - npm install
  - npm run build
  - knex migrate:latest --env test
  - knex seed:run --env test

script:
  - npm test
  - istanbul cover --include-all-sources -x ./build/seeds/** -x ./build/migrations/** --root ./build ./node_modules/mocha/bin/_mocha test --report lcovonly && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
