notifications:
  email: false
branches:
  only:
  - master
  - electron-build
  - "/\\d+\\.\\d+\\.\\d+(-\\w+\\.\\d)$/"


matrix:
  include:
  - os: linux
    services: docker
    language: generic

  - os: osx
    osx_image: xcode9.3
    language: node_js
    node_js: "9"
    env:
      - ELECTRON_CACHE=$HOME/.cache/electron
      - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

script:
 - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
        docker run --rm -ti \
          --env-file <(env | grep -iE 'DEBUG|NODE_|ELECTRON_|YARN_|NPM_|CI|CIRCLE|TRAVIS_TAG|TRAVIS|TRAVIS_REPO_|TRAVIS_BUILD_|TRAVIS_BRANCH|TRAVIS_PULL_REQUEST_|APPVEYOR_|CSC_|GH_|GITHUB_|BT_|AWS_|STRIP|BUILD_') \
          --env ELECTRON_CACHE="/root/.cache/electron" \
          --env ELECTRON_BUILDER_CACHE="/root/.cache/electron-builder" \
          -v ${PWD}:/project \
          -v ${PWD##*/}-node-modules:/project/node_modules \
          -v ~/.cache/electron:/root/.cache/electron \
          -v ~/.cache/electron-builder:/root/.cache/electron-builder \
          electronuserland/builder:wine \
          /bin/bash -c "scripts/electron-build.sh"
    else
        scripts/electron-build.sh
