sudo: false

language: node_js

branches:
  only:
    - master

env:
  - CXX=g++-4.8

node_js:
  - "6.2"
  - "5.12"
  - "4.4"
  - "4.3"
  - "4.2"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8

before_script:
  - npm install

script:
  - npm run lint
  - travis_wait 30 npm run coverage
