env:
  global:
    - secure: "B0vgd3/83+GeQXtpNKAfVpNh+PQ2zV8Xa6uNevBF8cTFc5lPLtE7dOxLl5i5gkXgpcWCeoG7dN8vaplePYgxciJUOb8amFe6dOE/qtX+dUiv08kmu7XTYFuQlLX3kFzRgfvNN/gEslJrVLFTUJuxP+FdGJzFdceN9ytkJsfCDds+a0npMi5QsgHQ4IWemTQ+9mF78sL0OkTeV5sZMACFA8Bm7bb3o8Xo679nkdS0+BiAKA4CoZuQ/E/5ivmpUi3d2M9vk7Y74fKus5slNeM8jax1z6n3C/mJN9s7pGFph3jUWd0UhssGvbp/X2O5Wnh2nnVaPYWMhyyE4bsQWpj9xE/URZYYOEX+YAc/E3+SYfOh0zU6E+DuI6aZQ/Z9LhGvmNBq5OCd0PUw4VXZrXAQqSIYfFLeTMgkW7fa7rJRxn+TF7GU9Yeuqv07eT/2fIgfvNKtj6hJsXdqpcU/IAsavkZ4+0Pf9CpJwmTemBLzZyaP/nDHBwz/c5OWJx2W6KFjdI/1+orI9Y/0DGbSpNK1wcUFEMk9+Qm1crE7lmxzSP0dQ3FpsRpq2uSrq/EwYMxTsYyfa7uhlExXYFcTYilmSdMyGII2mSNzkw0LHcjYb8mNpfW0ZHV3Y5xe0mXz7Zg407bLN29KQnTemDvw2/aX5xTOsQFzwacdLtlNkKJ3K64="
    - secure: "yY8Ky8QVFsJtMlBhmNOqmuSAKddRZWeFA62FvkzF4PEAWLKGAQy5cOjzEicCQdhTiOC/oM3LWkLVH85OcQIaE7Z8IGmXzEJPlFs7w4DjU2vaSwWOt3n2IbgxuBKBRolEUByZHGai9oqe1WcM61fVh2GEuaAk/8JbBHslT8C6A47Uzsja0gHTZZQq90JRpOX6O+joe+ZBH7z0MV/oY2E6GGa75bVBFiZptuqcB1rWFdT5b6tHEMDJ1Of2A4yNfF52j5Lk+HWNVARFSO0IPxpcX763vaeiYQ/OLuzlBtN7K7aQizONw8pg/1ukQYAmOu+eQtQj3pTXCL0H3f8msNql4ksJlHXkHWJr1eYO+vpZr9xjCLs29fHTJQYl+QHqG/pOJKIMoCDQruUZwFcS8Yu3ZY8evugM0Sz9BHkKgaUVAxpyuurkDuUaHA4IQu05IbBbj5VwP4QHDwpvI/VMM4mrFmUIeW73GDFfvsAs6U635XzVEvE7IleN5nmkxTBh1vxH436xhmMPYWAoRwpI/LTA5/pNut4H2EyFNybotpPzy1oloAH/u7uw57oNbA/UKtxwaUtEp7n95Aqba+cr9xYJ48kY8Ro/GmIeXOW1GJC7r4qCbnmUr5tPlqtaGwDClzKpLJ9D6rc6GC5aO1iUnhbL+pHCbGBA8L7a4Q4zZihD3HA="
notifications:
  email: false
branches:
  only:
  - master
  - electron-build
  - "/v\\d+\\.\\d+\\.\\d+(-\\w+\\.\\d)$/"


matrix:
  include:
  - os: linux
    services: docker
    sudo: required
    language: generic

  - os: osx
    osx_image: xcode9.3
    language: node_js
    node_js: "9"
    env:
      - ELECTRON_CACHE=$HOME/.cache/electron
      - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
      - CSC_IDENTITY_AUTO_DISCOVERY=false

script:
 - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
        docker run --rm -ti \
          --env-file <(env | grep -iE 'DEBUG|NODE_|ELECTRON_|YARN_|NPM_|CI|CIRCLE|TRAVIS_TAG|TRAVIS|TRAVIS_REPO_|TRAVIS_BUILD_|TRAVIS_BRANCH|TRAVIS_PULL_REQUEST_|APPVEYOR_|CSC_|GH_|GITHUB_|BT_|AWS_|STRIP|BUILD_') \
          --env ELECTRON_CACHE="/root/.cache/electron" \
          --env ELECTRON_BUILDER_CACHE="/root/.cache/electron-builder" \
          -v ${PWD}:/project \
          -v ${PWD##*/}-node-modules:/project/node_modules \
          -v ~/.cache/electron:/root/.cache/electron \
          -v ~/.cache/electron-builder:/root/.cache/electron-builder \
          electronuserland/builder:wine-mono \
          /bin/bash -c "scripts/electron-build.sh"
    else
        travis_wait scripts/electron-build.sh
    fi
