# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'Ubuntu 16.04'

strategy:
  matrix:
    node_8_x:
      node_version: 8.x
    node_9_x:
      node_version: 9.x

steps:
- script: |
    yarn install --ignore-scripts --frozen-lockfile
    git config --global user.email "team@augur.net"
    git config --global user.name "Augur Developers"
    lerna run build --stream --scope augur-core
    lerna run build --stream --scope augur-node
  displayName: 'build and test'
