# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'Ubuntu 16.04'

strategy:
  matrix:
    node_8_x:
      node_version: 8.x
    node_9_x:
      node_version: 9.x

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.6.5'

- script: |
    yarn install --ignore-scripts --frozen-lockfile
    git config --global user.email "team@augur.net"
    git config --global user.name "Augur Developers"
    python -m pip install --upgrade pip setuptools wheel
    pip install virtualenv
    pip install --upgrade pip setuptools
    pip install --upgrade pip-tools
    pip install -r requirements.txt
  displayName: 'setup'

- script: |
    #env
    #echo $PATH
    #PATH=$PATH:node_modules/.bin
    yarn workspace augur-core run build
    yarn workspace augur-node run build
  displayName: 'build and test'
