version: '3.5'

volumes:
  nginx-shared:

services:
  nginx:
    image: nginx:1.13-alpine
    hostname: nginx
    ports:
      - "8000:8000"
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
      - nginx-shared:/nginx
    depends_on:
      - web
    networks:
      - augur
  db:
    image: postgres:10-alpine
    ports:
      - "5432:5432"
    networks:
      - augur
  web:
    image: augurproject/safe-relay-service_web:latest
    env_file:
      - .env
    depends_on:
      - db
      - redis
    working_dir: /app
    ports:
      - "8888:8888"
    volumes:
      - nginx-shared:/nginx
    command: docker/web/run_web.sh
    networks:
      - augur

  redis:
    image: redis:4-alpine
    ports:
      - "6379:6379"
    networks:
      - augur

  worker: &worker
    image: augurproject/safe-relay-service_web:latest
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - web
    command: docker/web/celery/worker/run.sh
    networks:
      - augur

  scheduler:
    <<: *worker
    command: docker/web/celery/scheduler/run.sh
    networks:
      - augur

  0x-mesh:
    image: 0xorg/mesh:0xV3
    hostname: 0x
    ports:
      - 60557:60557
      - 60558:60558
      - 60559:60559
    environment:
      - ETHEREUM_CHAIN_ID=${ETHEREUM_CHAIN_ID}
      - CUSTOM_CONTRACT_ADDRESSES=${CUSTOM_CONTRACT_ADDRESSES}
      - ETHEREUM_RPC_URL=http://geth:8545
      - USE_BOOTSTRAP_LIST=false
      - BLOCK_POLLING_INTERVAL=1s
      - ETHEREUM_RPC_MAX_REQUESTS_PER_24_HR_UTC=169120
      - VERBOSITY=6
    networks:
      - augur

networks:
  augur:
    name: augur
